name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@skakarh"
          max_post_count: "5"
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update with latest blog posts"
          git push https://x-access-token:${{ secrets.BLOG_POSTS_SECRET }}@github.com/ShahnawazKakarh/ShahnawazKakarh.git HEAD:main
        env:
          BLOG_POSTS_SECRET: ${{ secrets.BLOG_POSTS_SECRET }}
